services:
  - type: web
    name: soul-v2-frontend
    env: static
    rootDir: v2-modern
    buildCommand: npm install && npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
